export type SongIniOptions = {
	name: string;
	artist: string;
	album?: string;
	year?: string;
	genre?: string;
	charter?: string;
	songFile?: string;
};

export function writeSongIni(options: SongIniOptions): string {
	const lines = [
		`[song]`,
		`name = ${options.name}`,
		`artist = ${options.artist}`,
		`charter = ${options.charter ?? "CHDG"}`,
		`album =${options.album ? ` ${options.album}` : ""}`,
		`genre =${options.genre ? ` ${options.genre}` : ""}`,
		`year =${options.year ? ` ${options.year}` : ""}`,
		`song_length =`,
		`diff_drums = 0`,
		`preview_start_time = 0`,
		`icon =`,
		`loading_phrase = Generated by CHDG`,
		`song = ${options.songFile ?? "song.ogg"}`,
		``,
	];

	return lines.join("\n");
}
